name: Build native Windows executable

on:
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
      
      - name: Clean and build fat JAR
        run: ./gradlew clean shadowJar
      
      - name: Create native image from fat JAR
        run: |
          native-image --no-fallback --enable-http --enable-https --verbose \
          -jar build/libs/labv-sftp-transfer-all.jar \
          -H:Name=labv-sftp-transfer \
          -H:+ReportExceptionStackTraces \
          -H:+PrintAnalysisCallTree \
          -H:Log=registerResource \
          -H:+UnlockExperimentalVMOptions
      
      - name: Upload native executable
        uses: actions/upload-artifact@v4
        with:
          name: labv-sftp-transfer.exe
          path: labv-sftp-transfer.exe
          
      - name: Run native image to test behavior
        run: |
          .\labv-sftp-transfer.exe --dry-run
